name: quasar-deploy
on:
  push:
    branches:
      - master
jobs:
  j_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Yarn
        run: yarn install
      - name: Build with Quasar
        run: yarn quasar build
      - name: Archive artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: Collect dist
          path: dist/
  j_deploy:
    needs: j_build
    runs-on: ubuntu-latest
    steps:
      - name: prova
        run: echo "BuIlD!"
      - name: prova2
        run: echo "prova2"
